layout_spectrum: 0.5232975
typography_spectrum: 0.6407966
color:
  saturation: 0.3602151
  brandStrength: 0.5402486
  lightness: 0.9032258
  rhythmicContrast: 0.672043
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Deniz
